name: Download Instagram Video

on:
  workflow_dispatch:
    inputs:
      url:
        description: "Instagram URL"
        required: true

jobs:
  download:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install yt-dlp
        run: pip install yt-dlp

      - name: Download Video
        run: yt-dlp "${{ github.event.inputs.url }}" -o video.%(ext)s

      - name: Upload Video
        uses: actions/upload-artifact@v4
        with:
          name: downloaded-video
          path: video.*
